
;VERY IMPORTANT: Y AND Z ARE INVERTED WHEN COMPARED TO BLENDER!
;MUITO IMPORTANTE: Y E Z S�O INVERTIDOS QUANDO COMPARADOS AO BLENDER!

[mod]
name=BMC Procity 12LF
busModVersion=1
preview=preview.png

[config]
baseDir=BMC Procity 12LF
lights1=lights1.txt
engine1auto=engine1auto.txt
engine1manual=engine1manual.txt
wheels1=wheels1.txt
sounds1=sound.txt
models1=models12LF.txt

[folders]
skins=skins
textures=textures

[doors]
rightdoor1=rightdoor1.txt
rightdoor2=rightdoor2.txt
rightdoor3=rightdoor3.txt

[data]
template=4x2
mass1=16000

[posJoint1]
posX=0
posY=0.480852
posZ=-4.45523

[posCenterOfMass1]
posX=0
posY=0.517496
posZ=0.48266

[collision1]
posX=0
posY=1.78297 
posZ=-0.18372
sizeX=2 
sizeY=2.7101 
sizeZ=11.8735

[leftMirror]
posX=-1.31239
posY=2.25195
posZ=5.26249
rotX=
rotY=
rotZ=

[rightMirror]
posX=1.28867
posY=2.25195
posZ=5.99256
rotX=
rotY=
rotZ=

[middleMirror]
posX=0.198049
posY=2.6486
posZ=5.41858
rotX=4.46107
rotY=-15.0983
rotZ=1.67575

[posDriverHead]
posX=-0.636253
posY=1.89582
posZ=4.61893

[posPassengerCam1]
posX=0
posY=2.2175
posZ=-4.5073

[posDriverHumanoid]
posX=-0.636253
posY=1.25266
posZ=4.72295

[posTicketTakerHumanoid]
enabled=0
posX=0.466703
posY=1.10903
posZ=1.37959
rotX=
rotY=
rotZ=

[posSmoke1]
enabled=1
posX=-1.13383
posY=0.418452
posZ=-5.76305
rotX=0
rotY=0
rotZ=0

[pathTurnstile1_1]
enabled=1
posX=0.334704
posY=0.933636
posZ=4.63964

[aeroSurface1_1]
posX=0
posY=0.522021
posZ=8.00262
drag=0.1
downforce=0.4

[aeroSurface1_2]
posX=0
posY=0.522021
posZ=2.74699
drag=0.1
downforce=0.4

[aeroSurface2_1]
posX=0
posY=0.522021
posZ=-7.43654
drag=0.1
downforce=0.4

[specialTextures]
cockpitBackgroundOn=dashboard_symbols_n.png
cockpitLightsOn=dashboard_symbols_n.png
pointersLightsOn=dashboard_symbols_n.png
externalLightsOn=lumini_n.png
internalLightsOn=lumini_n.png
stopRequestLightsOn=49n.png
passengerLightsOn=10N.png
multiplexOff=lumini.png
multiplexOn=lumini_n.png
multiplexActive=lumini_n.png



## FALTA FAZER NO SISTEMA - AINDA NAO SUPORTADO
//configurador dos triggers das setas pro trafego na traseira
//luzes multiplex?
//luzes do ar condicionado e letreiro dele?
//camera de r�
//animacao da catraca
